FROM ubuntu:trusty

## This image is for decreasing the amount of coffee breaks during development.
## This base image prevents other images from also having to do apt-get update

RUN apt-get update -y

CMD ["/bin/true"]
